FIX Set empty date to null
silverstripe/silverstripe-contentreview pull request #263
Opened 2024-10-02 05:51 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/11403

2024-10-22 21:30 UTC, GuySartorelli requested changes

2024-10-22 21:30 UTC, GuySartorelli commented on src/Extensions/SiteTreeContentReview.php
> +            ;
```suggestion
```

2024-10-22 21:30 UTC, GuySartorelli commented on src/Extensions/SiteTreeContentReview.php
> +            $x=DBDate::create()->setValue($nextDateTimestamp)->Format(DBDate::ISO_DATE);
What is this `$x` variable??

2024-10-22 21:30 UTC, GuySartorelli commented on src/Extensions/SiteTreeContentReview.php
> +            $this->owner->NextReviewDate = null;
How would it be false? You updated the return values of `getReviewDate()` to _not_ return false.

2024-10-24 02:04 UTC, emteknetnz commented on src/Extensions/SiteTreeContentReview.php
> +            $x=DBDate::create()->setValue($nextDateTimestamp)->Format(DBDate::ISO_DATE);
Debug, have removed

2024-10-24 02:06 UTC, emteknetnz commented on src/Extensions/SiteTreeContentReview.php
> +            $this->owner->NextReviewDate = null;
I can't remember. Looking at that method it still has `return $page->obj('NextReviewDate');` so presumbably that was returning `false` in some circumstances

2024-10-29 04:27 UTC, emteknetnz commented on src/Extensions/SiteTreeContentReview.php
> +            ;
Was removed

2024-10-29 21:27 UTC, GuySartorelli commented on src/Extensions/SiteTreeContentReview.php
> +            $this->owner->NextReviewDate = null;
`obj()` _cannot_ return false, assuming `$page` is a `ModelData` (which `SiteTree` obviously is and therefore I think this is meant to be). It's explicitly typehinted to `?object`

2024-10-29 23:10 UTC, emteknetnz commented on src/Extensions/SiteTreeContentReview.php
> +            $this->owner->NextReviewDate = null;
Removed

2024-11-06 01:24 UTC, GuySartorelli approved these changes

2024-11-06 01:24 UTC, merged